# Default Configuration for ${pluginPrefix}
# Made by SirBlobman for v${pluginVersion}

# Should the plugin be allowed to check for updates?
update-checker: true

# These are the default health options for new players
# If you give access to some commands, players can set their own values

# Should player's hearts be scaled?
# This means they should only see 10 hearts (20 health), but they will still have all their health
# Default: true
scale-health: true

# Valid display types: BOSS_BAR, ACTION_BAR, NONE
# Default: BOSS_BAR
display-type: BOSS_BAR

# Should the player's health always be shown?
# If not, the health will only be shown when the player takes damage or heals
# Default: false
always-show: true

# Should hearts be displayed instead of health?
# Default: true
show-hearts: true

# Should spectators see the health of the entity they are spectating?
# Spectators will still see their own health if the entity they are spectating does not have health.
spectate-health: true
