# Default Configuration for ${bukkit.plugin.prefix}
# Made by SirBlobman for v${bukkit.plugin.version}

# These are the default health options for new players
# If you give access to some commands, players can set their own values
default-options:
  # Should player's hearts be scaled?
  # This means they should only see 20 hearts but they will still have all their health
  #
  # Default: true
  scale-health: true

  # Valid display types are listed below:
  # - BOSS_BAR
  # - ACTION_BAR
  # - BELOW_NAME
  #
  # Default: BOSS_BAR
  display-type: BOSS_BAR

  # Should the player's health always be shown?
  # If not, the health will only be shown when the player takes damage or heals
  #
  # Default: false
  always-show: false

  # Should hearts be displayed instead of health?
  #
  # Default: true
  show-hearts: true

messages:
  display-health: "&2HP: &c{health}/{max_health}"
  display-hearts: "&c{hearts}/{max_hearts} &4&l\u2764"
  display-absorption-health: "&e+ {absorb_health}"
  display-absorption-hearts: "&e+ {absorb_hearts} &6&l\u2764"

  commands:
    no-permission: "&4You do not have the &c{permission}&4 permission."
    not-player: "&4You are not a player."

    compressed-hearts:
      help:
        - "&6&lCommand Usage:"
        - "&6/compressed-hearts help&e: View this help page."
        - "&6/compressed-hearts compress&e: Compress or uncompress your hearts."
        - "&6/compressed-hearts display <boss/action/below-name>&e: Change the display type of your health."
        - "&6/compressed-hearts reload&e: Reload the config for this plugin."

      compress:
        enabled: "&aYour health bar is now scaled."
        disabled: "&aYour health bar is no longer scaled."

      display: "&aSuccessfully changed your display type to &c{display-type}&a."
      reload: "&aSuccessfully reloaded the CompressedHearts config.yml."

    hp:
      invalid-target: "&4Could not find player by name &c{target}&4."

      self:
        - "&6&lYour Information:"
        - "&6Health: &e{health}"
        - "&6Hearts: &e{hearts}"
        - "&6Absorption Health: &e{absorb_health}"
        - "&6Absorption Hearts: &e{absorb_hearts}"

      other:
        - "&6&l{target}'s Information:"
        - "&6Health: &e{health}"
        - "&6Hearts: &e{hearts}"
        - "&6Absorption Health: &e{absorb_health}"
        - "&6Absorption Hearts: &e{absorb_hearts}"